### ISSUE TITLE
Backstack lost when coming from Recents

### ISSUE THREAD

**Issue by amlcurran** [malmstein/yahnac#10]
When viewing an article and then going to recents, you can't get back to the main article list without launching it from the launcher

Repro steps:
- Open an article
- Press the home button
- Press recents and select yahnac
- Press the back (or up) button on the article view

Expected result:
The app will go back to the list of articles

Actual result:
The app exits and you return to your previous app.

Thanks :)

**Comment by malmstein** [comment]
Thanks @amlcurran!

**Comment by malmstein** [comment]
Fixed on https://github.com/malmstein/yahnac/pull/11/files
