### ISSUE TITLE
Undo bookmark/unbookmark didn't update "Bookmark" button state

### ISSUE THREAD

**Issue by hotpro** [malmstein/yahnac#12]
When viewing an article,  bookmark/unbookmark it then undo bookmark/unbookmark didn't update "Bookmark" button state in actinBar.

Repro steps:

Open an article
Click the "Bookmark" button to add it to bookmark. 
The "Bookmark" button get checked. 
A message view show at the bottom with an "Undo" button. 
Click "Undo" button.

Expected result:
The "Bookmark" button get unchecked. 

Actual result:
The "Bookmark" button is still checked.

**Comment by malmstein** [comment]
Fixed https://github.com/hotpro/yahnac/commit/c2b451cbcc54c8c4a517708757befe69abcd7f04
