### ISSUE TITLE
Zoom buttons display on the navigation bar

### ISSUE THREAD

**Issue by JaspervanRiet** [malmstein/yahnac#20]
Don't think this one is going to require much description. In the newest update, scroll up or down in the in-app browser. (Look at the navbar). Moto G, 5.1

![2015-06-21 19 06 03](https://cloud.githubusercontent.com/assets/5138348/8272973/a53f72fa-1859-11e5-9f79-6ab59dea90b1.png)

**Comment by malmstein** [comment]
that's awful! Will look into it @JaspervanRiet

**Comment by malmstein** [comment]
@JaspervanRiet the last version of the app has removed the zoom controls, have you checked it out?

**Comment by JaspervanRiet** [comment]
@malmstein Yea works fine on my device. You can close the issue.

**Comment by malmstein** [comment]
:+1:
