### ISSUE TITLE
Share icons in article and comments menus too big

### ISSUE THREAD

**Issue by ethanmad** [malmstein/yahnac#23]
The menu icons in `menu_comments.xml` are different sizes; the share icons from `action_share` are bigger than the normal size for a menu icon. They should be 24dp ([guidelines](http://www.google.com/design/spec/style/icons.html#icons-system-icons)), but appear to be 36dp instead. The icons for `action_article` and `action_bookmark` and the up button are the correct size.

I tried fixing the share button by adding `android:icon="@drawable/ic_share" ` (to at least set the share icon to the correct size, as the `ic_share` draw able is the correct size) to the item, but I didn't see any change as a result.

Got help from @Chainfire and tried: http://stackoverflow.com/a/24472038 & http://stackoverflow.com/a/21922282. The icon changed, but it got for some reason it scaled up and became blurry, so neither worked (I tried with your `@drawable/ic_share` and the built in `@drawable/abc_ic_menu_share_mtrl_alpha`).

I think android.support.v7.widget.ShareActionProvider just hasn't been updated to meet the new guidelines.

Possible solution: switch to another share implementation. I wouldn't mind attempting to handle this; it would be a good learning experience for me. Any suggestions/thoughts?

Great client, by the way. Installed it yesterday and I've really been enjoying it. Seems very well written, too.

**Comment by malmstein** [comment]
thanks @ethanmad, I'll take a look asap!

**Comment by malmstein** [comment]
@ethanmad do you still see a difference?

**Comment by ethanmad** [comment]
I had been using a different HN client for some reason until your reply. I didn't notice any issues upon reinstalling. Definitely sticking with yahnac now--it's really far ahead of everything else I've used.

**Comment by malmstein** [comment]
thanks @ethanmad! I hope new updates will convince you to use Yahnac again! :)

**Comment by ethanmad** [comment]
Oh, I've switched back to it. The only thing bugging me now is the links
not showing.
