### ISSUE TITLE
Utilize Chrome Custom Tabs Feature

### ISSUE THREAD

**Issue by Nemisis** [malmstein/yahnac#27]
I think it could be useful to utilize the new [Chrome Custom Tabs](http://developer.android.com/intl/zh-cn/tools/support-library/features.html#custom-tabs) that has come out for the in app browser. Some benefits: 

 * Uses a Chrome instance, so logins and such will be used in the app. 
 * Will still look like a normal WebView within the app
 * Can pre-load URLs. I think a good use case for this would be when a user reads the comments, they could pre-load the URL

Just an idea.

**Comment by malmstein** [comment]
Thanks for this @Nemisis. It's a great idea indeed!

**Comment by malmstein** [comment]
Solved!
