### ISSUE TITLE
Links appear to be invisible

### ISSUE THREAD

**Issue by peteryates** [malmstein/yahnac#29]
Can't tell if the text is white or not there at all

This happens on my Nexus 6P, screenshot below, the hyperlink should be on the third line (where the gap followed by a slash is)

![Screenshot](http://i.imgur.com/szFNGA9.png)

**Comment by malmstein** [comment]
thanks @peteryates, I'll take a look asap!

**Comment by ethanmad** [comment]
I'm getting the same issue (Nexus 6, Android 6.0.1).

**Comment by Plastix** [comment]
I'm getting the same issue on my Nexus 5 running Android 6.0.1.

**Comment by malmstein** [comment]
@peteryates @ethanmad @Plastix I've found the issue, a new update is being uploaded to Google Play right now. Thanks for the heads up, this issue is not happening in Lollipop :boom:

**Comment by ethanmad** [comment]
Looks good to me!

**Comment by peteryates** [comment]
Me too, thanks for the fix

**Comment by Plastix** [comment]
Thanks for the quick fix!
