### ISSUE TITLE
Fix Travis-CI support.

### ISSUE THREAD

**Issue by pedrovgs** [malmstein/yahnac#31]
@malmstein assign me this issue and I'll fix it tomorrow ;)

**Comment by malmstein** [comment]
hey @pedrovgs I made you collaborator, otherwise it can't be assigned :dancer:

**Comment by pedrovgs** [comment]
haha sorry I always forgot that. Remove me as collaborator, I'll send you a PR from my fork.

**Comment by malmstein** [comment]
fixed by @pedrovgs https://github.com/malmstein/yahnac/pull/33
